apiVersion: v1
kind: ReplicationController
metadata:
  name: sula-scala
spec:
  replicas: 5
  selector:
    app: sula
  template:
    metadata:
      name:  sula-scala
      labels:
        app: sula
    spec:
      containers:
        - name: sula-rc
          image: docker pull hseeberger/scala-sbt
          ports:
            - containerPort: 8080
            